name: Build and Publish storybook to GitHub Pages

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@ComponentSpirit'
      - name: 'Install dependencies'
        run: yarn install --immutable
      - name: 'Compile library'
        run: yarn run build
      - name: 'Publish the package to GitHub Packages'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
